### ISSUE TITLE
reload_configuration timeouts after service restart

### ISSUE THREAD

**Issue by sed-i** [canonical/prometheus-operator#136] opened 2021-10-01 14:51 UTC
https://github.com/canonical/prometheus-operator/blob/ccc2858ac1b2c8d1a4dc1a0293969b94687598f0/src/charm.py#L123

When I `juju config scrape-config`, then prometheus tries to reload configuration but the workload is probably not running yet.

```
  File "./src/charm.py", line 123, in _configure
    reloaded = self._prometheus_server.reload_configuration()
  File "/var/lib/juju/agents/unit-prometheus-0/charm/src/prometheus_server.py", line 38, in reload_configuration
    response = post(url, timeout=self.api_timeout)
  File "/var/lib/juju/agents/unit-prometheus-0/charm/venv/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/var/lib/juju/agents/unit-prometheus-0/charm/venv/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/lib/juju/agents/unit-prometheus-0/charm/venv/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/juju/agents/unit-prometheus-0/charm/venv/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/juju/agents/unit-prometheus-0/charm/venv/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=9090): Read timed out. (read timeout=2.0)
unit-prometheus-0: 14:46:05.350 ERROR juju.worker.uniter.operation hook "metrics-endpoint-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by balbirthomas** [comment] 2021-11-29 12:52
@sed-i I am unable to reproduce this issue using `juju config` directly for the Prometheus charm (for example `juju config prometheus-k8s evaluation-interval=45s`). I presume you are using the Prometheus scrape config charm and setting a configuration option on the scrape config charm. Is this correct ? Could you please provide steps to reproduce this issue if possible ? Is it still happening ?

**Comment by sed-i** [comment] 2021-11-29 14:49
Can't reproduce atm with the steps above.
Feel free to close, will reopen if happens again.

**Comment by balbirthomas** [comment] 2021-11-29 15:01
OK. Closing. Even though it would be trivial to trap the `ReadTimeout` exceptions let us wait and see if these happen again so we can analyse in detail the cause of these problems and "cure the disease rather than treat the symptom".

**Closed by balbirthomas** 2021-11-29 15:01 UTC
Labels: bug
