### ISSUE TITLE
Can't configure custom Prometheus configuration

### ISSUE THREAD

**Issue by jonatasbaldin** [canonical/prometheus-operator#19] opened 2021-03-04 09:37 UTC
The Prometheus Charm doesn’t seem to have an easy way to configure any custom scrapping. The default configuration (`prometheus.yaml`) is hardcoded by the `_prometheus_config(self)` method and only scrapes itself.

With that, it’s not possible to configure the Prometheus Charm to scrape anything else, like other deployed Charms or Juju itself.

Is that assumption correct or am I missing something?

**Comment by balbirthomas** [comment] 2021-03-04 10:52
Hi @jonatasbaldin . At present there is a [branch](https://github.com/balbirthomas/prometheus-operator/tree/k8s-discovery) available that supports automatic discovery of scrape targets for Kubernetes clusters. The automatic discovery feature was removed after code review because the intention was to make configuration of scrape targets explicit by providing this information through relation data of any application that forms a relation with the Prometheus charm. This feature has not yet been implemented. 

Would it be sufficient if the Prometheus charm accepted a YAML scrape configuration from the client charm over application relation data ? Do you have any specific application charm in mind that you would like to relate with the Prometheus charm ?

ATTN: @jlounder would accepting YAML over relation data be an acceptable solution ?

**Comment by jonatasbaldin** [comment] 2021-03-04 11:54
I think a good solution would be to accept the whole `prometheus.yaml` file, like a config specifying the path to the file.

What do u think?

**Comment by balbirthomas** [comment] 2021-03-04 11:57
> I think a good solution would be to accept the whole `prometheus.yaml` file, like a config specifying the path to the file.

This is a bit risk isn't it ? The same Prometheus charm may be used by multiple client charms. If one client charm is allowed to overwrite the entire Prometheus config, it could interfere with Prometheus scrapping targets for other clients. This does this sound reasonable ?

**Comment by balbirthomas** [comment] 2021-03-04 12:01
> I think a good solution would be to accept the whole `prometheus.yaml` file, like a config specifying the path to the file.

Further to my point abovet. A config options that accepts a full `prometheus.yaml` can be implemented, if this will suit your use case. One limitation of this approach is that the administrator will need to provide and updated config file for every relation they add to the Prometheus charm.

**Comment by jameinel** [comment] 2021-03-04 13:09
I wouldn't make it a complete Prometheus.yaml, but being able to specify
scrape targets (which would then be merged with relation targets, etc)
would be useful.

**Comment by balbirthomas** [comment] 2021-03-04 16:02
@jameinel @jonatasbaldin I have created a prototype on the [scrape-config](https://github.com/balbirthomas/prometheus-operator/tree/scrape-config) branch of my fork. This prototype adds a `scrape-config` option to the charm config. The value of which is the scrape config in YAML format as per Prometheus documentation. Please see commit message for details of config value.  A [sample charm config file](https://github.com/canonical/prometheus-operator/files/6084913/config.txt) is attached. The included scrape config is the same as the sample automated discovery config provided by Prometheus documentation. Using this file you should be able to deploy the Prometheus charm as in `juju deploy ./prometheus.charm --config config.yaml`. 

Please note this is a prototype. I am only posting it here for early feedback and further discussion. It has not been reviewed, the feature/implementation has not been approved, and there are no unit tests. I did manually run it myself and it seems to work.

**Comment by jonatasbaldin** [comment] 2021-03-05 11:01
I couldn't get this working :( Prometheus starts up, but there are tons of logs like: 
```
prometheus-0 prometheus level=error ts=2021-03-05T08:51:29.597Z caller=klog.go:96 component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1.Pod: failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:my-model:default\" cannot list resource^Cn ts=2021-03-05T08:51:40.166Z caller=scrape.go:1372 component="scrape manager" scrape_pool=prometheus target=http://localhost:9090/metrics msg="Error on ingesting out-of-order samples" num_dropped=661
```

Here's I think what is happening:

- The `prometheus-0` Pod mounts the `default` ServiceAccount from the namespace where it is deployed
- The said ServiceAccount is not tied to any kind of ClusterRoleBinding, so it lacks permissions to read all sorts of Cluster-level metrics from K8s

What do u think?

**Comment by balbirthomas** [comment] 2021-03-05 11:07
> What do u think?

I think you may be right on this one @jonatasbaldin . Could you attach more information on your setup and scrape_config so I can reproduce the issue. Though perhaps we should create a separate issue for this one, since the feature is related to integrating Prometheus charm's behaviour with k8s RBAC.

**Comment by jonatasbaldin** [comment] 2021-03-05 11:14
Right!

- Code: I'm using your fork with the mentioned branch and configuration
- Kubernetes v1.17.0 under Kind v0.7.0
- Juju version is 2.9-rc6-catalina-amd64

Here are some interesting outputs

The ServiceAccount mounted on the Pod:
```
$ kubectl describe pod -n my-model prometheus-0
[...]
  default-token-drxtp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-drxtp
    Optional:    false
```

Confirming is the `default` ServiceAccount from the `my-model` namespace by comparing the names:
```
$ kubectl describe serviceaccounts -n my-model default 
Name:                default
Namespace:           my-model
Labels:              <none>
Annotations:         <none>
Image pull secrets:  <none>
Mountable secrets:   default-token-drxtp
Tokens:              default-token-drxtp
Events:              <none>
```

Listing all the ClusterRoleBindings and RoleBindings, filtering by the word `default` (result is empty):
```
$ kubectl get rolebindings,clusterrolebindings --all-namespaces -o custom-columns='KIND:kind,NAMESPACE:metadata.namespace,NAME:metadata.name,SERVICE_ACCOUNTS:subjects[?(@.kind=="ServiceAccount")].name' | grep default
```

**Comment by jonatasbaldin** [comment] 2021-03-05 13:52
Hey @balbirthomas, did some investigation and found a solution!

Adding this block into the spec enables Prometheus to fetch data from the Kubernetes API:
```

            'serviceAccount': {
                'roles': [{
                    'global': True,
                    'rules': [
                        {
                            'apiGroups': [''],
                            'resources': [
                                'nodes',
                                'nodes/proxy',
                                'nodes/metrics',
                                'services',
                                'endpoints',
                                'pods',
                                'ingresses',
                                'configmaps'
                            ],
                            'verbs': ['get', 'list', 'watch'],
                        },
                        {
                            'apiGroups': [
                                'extensions',
                                'networking.k8s.io',
                            ],
                            'resources': [
                                'ingresses',
                                'ingresses/status',
                            ],
                            'verbs': ['get', 'list', 'watch'],
                        },
                        {
                            'nonResourceURLs': ['/metrics'],
                            'verbs': ['get'],
                        },
                    ]
                }]
            }
```

These rules are from the [Prometheus Helm Chart](# From: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/templates/server/clusterrole.yaml).

Do you want to add this to your branch and open a PR?

**Comment by balbirthomas** [comment] 2021-03-05 13:54
> Do you want to add this to your branch and open a PR?

Hi @jonatasbaldin . Glad that worked. Yes please create a PR. I will discuss it with team and review. Thank you very much.

**Comment by jonatasbaldin** [comment] 2021-03-05 13:56
Could you create a PR with your changes + this block? It doesn't do anything without the `scrape-config` configuration.

**Comment by balbirthomas** [comment] 2021-03-05 14:01
> Could you create a PR with your changes + this block? It doesn't do anything without the `scrape-config` configuration.

Yes I will do. Let me write a unit test. You may want to do the same if it is possible (or I could try it myself once you make your PR). Give me some time I will get back to you.

**Comment by balbirthomas** [comment] 2021-03-05 14:33
@jonatasbaldin FYI: https://github.com/canonical/prometheus-operator/pull/20

**Comment by jonatasbaldin** [comment] 2021-03-05 14:49
Thanks!

I was thinking: what would be the best practice to add custom RBAC rules?

1. Just add them in the `pod_spec`, hardcoded.
2. Add a `service_account` config value and parse into the `pod_spec` (as you did with the `scrape-config`).
3. Other way?

**Comment by balbirthomas** [comment] 2021-03-05 15:00
@jonatasbaldin Those are good questions. My thoughts

1.  With regard to implementation detail - kindly do consider wrapping generation of service account rules into a function, that is called by `_prometheus_config`.
2.  Even if we choose to add a charm configuration options `service-account` I am inclined to think it will be nice to have a default so that the common deployment  command line use case is very simple. For `scrape-config` I could not think of a better default than what already existed. I will give a bit more thought to what would be a good default for k8s RBAC and post here if anything. I feel your example above is a good starting point. Thoughts ? 

Does this sound reasonable ?

It will be great to have @jameinel and @jlounder input on this issue too.

**Comment by balbirthomas** [comment] 2021-03-09 09:31
> Hey @balbirthomas! I opened #21 to add a default RBAC configuration and we can work further on a custom field for the `config.yaml`. What do you think?

Hi @jonatasbaldin Left you one comment on PR. Looks good otherwise. However I understand the desired product design is to have such configuration passed over relation events as structured data. You may want to request @jlounder for a review on this even if you need this as a stop gap measure.

**Comment by balbirthomas** [comment] 2021-05-04 09:23
Ability to add a custom scrape configuration using command line config option has been merged into master. Hence I am closing this issue now. Future revisions may add support for ingesting scrape targets through relation data.

**Closed by balbirthomas** 2021-05-04 09:23 UTC
Labels: enhancement
